server:
    port: 8204

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-enums-package: cn.edu.scnu.ssyx.enums

feign:
    sentinel:
        enabled: true
    client:
        config:
            default:
                connect-timeout: 30000
                read-timeout: 50000
spring:
    main:
        allow-bean-definition-overriding: true
    elasticsearch:
        rest:
            uris: http://localhost:9200
    rabbitmq:
        host: 192.168.10.128
        port: 5672
        username: guest
        password: guest
        publisher-confirm-type: CORRELATED
        publisher-returns: true
        listener:
            simple:
                prefetch: 1
                concurrency: 3
                acknowledge-mode: manual   #消费端手动确认
    redis:
        host: localhost
        port: 6379
        database: 0
        timeout: 1800000
        password:
        lettuce:
            pool:
                max-active: 20 #最大连接数
                max-wait: -1    #最大阻塞等待时间(负数表示没限制)
                max-idle: 5    #最大空闲
                min-idle: 0     #最小空闲