spring:
    application:
        name: service-search
    cloud:
        nacos:
            username: nacos
            password: nacos
            discovery:
                server-addr: localhost:8848
    profiles:
        active: dev
